name: CBD
on:
  push:
    branches:
      - main
jobs:
  cbd:
    name: doc cbd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn && yarn run deploy
      - name: DeployGP
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: DeployECS
      - uses: easingthemes/ssh-deploy@v2
      - env:
          ARGS: "-avz --delete"
          SSH_PRIVATE_KEY: ${{ secrets.ECS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.ECS_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.ECS_REMOTE_USER }}
          SOURCE: "dist"
          TARGET: "/www/static/doc/bruce"
